### ISSUE TITLE
데이터 추가 / 새 테이블에 데이터 추가 시 발생한 오류 (2)

### ISSUE THREAD

**Issue by ssm0219** [mobigen/IRIS-BigData-Platform#1312]
## 버그 설명 ##
#1311 과 동일한 조건에서 컬럼명의 빈칸을 '_'로 교체한 뒤 import를 진행했더니,
size가 작은 sample 데이터에서는 정상적으로 되었으나, 원래 데이터로 진행햇더니 아래와 같은 로그를 뱉고 정상 종료되지 않았습니다.

## 재현하는 방법 ##
원 데이터: https://drive.google.com/file/d/1HkgmpCgjk7EJpRS7egyMEH_qPsTCAids/view?usp=sharing

진행방식은 #1311 과 동일하며, 참고하실 수 있도록 아래 스크린샷을 첨부하였습니다.

## 스크린샷 ##
#1311 과 동일한 스크린샷이지만 파일은 위에 구글 드라이브 링크 드린 걸로 하셔야 합니다.

1)
![데이터추가_오류(1)](https://user-images.githubusercontent.com/35832986/57065502-98a8b200-6d04-11e9-946b-8f741be6ec16.JPG)

2)
![데이터추가_오류(2)](https://user-images.githubusercontent.com/35832986/57065508-9d6d6600-6d04-11e9-91a4-40361f2dcc2d.JPG)

3)
![데이터추가_오류(3)](https://user-images.githubusercontent.com/35832986/57065512-9fcfc000-6d04-11e9-9bed-4cf9300fa10d.JPG)

## 로그 ##

오류로그 첨부파일: [데이터추가_오류로그.txt](https://github.com/mobigen/IRIS-BigData-Platform/files/3137336/_.txt)
```
오류로그 내용:

새 테이블 생성에 성공 하였습니다.
데이터 전송을 시작 합니다.
Parameter Data
================================================================================
{
    "input_format": {
        "col_list": [
            "DR_Number", 
            "Date_Reported", 
            "Date_Occurred", 
            "Time_Occurred", 
            "Area_ID", 
            "Area_Name", 
            "Reporting_District", 
            "Crime_Code", 
            "Crime_Code_Description", 
            "MO_Codes", 
            "Victim_Age", 
            "Victim_Sex", 
            "Victim_Descent", 
            "Premise_Code", 
            "Premise_Description", 
            "Weapon_Used_Code", 
            "Weapon_Description", 
            "Status_Code", 
            "Status_Description", 
            "Crime_Code_1", 
            "Crime_Code_2", 
            "Crime_Code_3", 
            "Crime_Code_4", 
            "Address", 
            "Cross_Street", 
            "STIME", 
            "X", 
            "Y", 
            "PARTITION_KEY"
        ], 
        "col_sep_list": [
            "|"
        ], 
        "header": "1", 
        "multi_sep": "0", 
        "row_sep_list": [
            "\n", 
            "\r\n"
        ], 
        "text_qualifier": ""
    }, 
    "output_format": {
        "col_sep_list": [
            "|"
        ], 
        "column_info": [
            {
                "name": "DR_Number", 
                "type": "TEXT"
            }, 
            {
                "name": "Date_Reported", 
                "type": "TEXT"
            }, 
            {
                "name": "Date_Occurred", 
                "type": "TEXT"
            }, 
            {
                "name": "Time_Occurred", 
                "type": "TEXT"
            }, 
            {
                "name": "Area_ID", 
                "type": "TEXT"
            }, 
            {
                "name": "Area_Name", 
                "type": "TEXT"
            }, 
            {
                "name": "Reporting_District", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code_Description", 
                "type": "TEXT"
            }, 
            {
                "name": "MO_Codes", 
                "type": "TEXT"
            }, 
            {
                "name": "Victim_Age", 
                "type": "INTEGER"
            }, 
            {
                "name": "Victim_Sex", 
                "type": "TEXT"
            }, 
            {
                "name": "Victim_Descent", 
                "type": "TEXT"
            }, 
            {
                "name": "Premise_Code", 
                "type": "TEXT"
            }, 
            {
                "name": "Premise_Description", 
                "type": "TEXT"
            }, 
            {
                "name": "Weapon_Used_Code", 
                "type": "TEXT"
            }, 
            {
                "name": "Weapon_Description", 
                "type": "TEXT"
            }, 
            {
                "name": "Status_Code", 
                "type": "TEXT"
            }, 
            {
                "name": "Status_Description", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code_1", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code_2", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code_3", 
                "type": "TEXT"
            }, 
            {
                "name": "Crime_Code_4", 
                "type": "TEXT"
            }, 
            {
                "name": "Address", 
                "type": "TEXT"
            }, 
            {
                "name": "Cross_Street", 
                "type": "TEXT"
            }, 
            {
                "name": "STIME", 
                "type": "TEXT"
            }, 
            {
                "name": "X", 
                "type": "TEXT"
            }, 
            {
                "name": "Y", 
                "type": "TEXT"
            }, 
            {
                "name": "PARTITION_KEY", 
                "type": "TEXT"
            }
        ], 
        "disk_savetime": 43200, 
        "header": "1", 
        "memory_savetime": 60, 
        "multi_sep": "0", 
        "partition_division": "STIME", 
        "partition_key": "PARTITION_KEY", 
        "partition_rangetime": 1440, 
        "row_sep_list": [
            "\n", 
            "\r\n"
        ], 
        "saving_method": "new", 
        "storage_type": "iris", 
        "table_method": "local", 
        "table_name": "SSM0219.LAPD_CRIME", 
        "text_qualifier": ""
    }, 
    "task_list": [
        {
            "func": "col_type_convert", 
            "param": {
                "col_list": [
                    {
                        "cellClass": "selected", 
                        "headerClass": "selected", 
                        "name": "Victim_Age", 
                        "prev_type": "TEXT", 
                        "type": "INTEGER"
                    }
                ]
            }
        }
    ], 
    "upload_file_list": [
        "LAPD_CRIMEDATA_from2010.csv"
    ]
}
--------------------------------------------------------------------------------

Data Pre-processing
================================================================================
Step.0 /app/tmp/6ee6ec39-b337-474f-ae29-e2a1fb6fa28a/LAPD_CRIMEDATA_from2010.csv
Step.1 Data Processing

<--- Last few GCs --->

[436:0x7f747b0311b0]    12776 ms: Mark-sweep 1015.7 (1064.9) -> 1015.5 (1067.4) MB, 372.0 / 0.0 ms  allocation failure GC in old space requested
[436:0x7f747b0311b0]    13121 ms: Mark-sweep 1015.5 (1067.4) -> 1015.5 (1036.4) MB, 345.0 / 0.0 ms  last resort GC in old space requested
[436:0x7f747b0311b0]    13535 ms: Mark-sweep 1015.5 (1036.4) -> 1015.5 (1036.4) MB, 413.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34659f898fe1 <JSObject>
    1: DoJoin(aka DoJoin) [native array.js:~94] [pc=0xa96b44dac27](this=0x34659f882241 <undefined>,o=0x2a66ae13241 <JSArray[1959459]>,p=1959459,D=0x34659f8822c1 <true>,z=0x2a66ae0c091 <String[1]\: \n>,y=0x34659f8822f1 <false>)
    2: Join(aka Join) [native array.js:~119] [pc=0xa96b44dd37e](this=0x34659f882241 <undefined>,o=0x2a66ae13241 <JSArray[1959459]>,p=1959459,z=0x2a66ae0c091 <String[1]\: \...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x7f747a0a7011 [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0xa96b43840bd
================================================================================
Data File: ./tmp/6ee6ec39-b337-474f-ae29-e2a1fb6fa28a/LAPD_CRIMEDATA_from2010.csv.trans.trans
Traceback (most recent call last):
  File "addon/iris-load/loader.py", line 257, in <module>
    main()
  File "addon/iris-load/loader.py", line 251, in main
    proc (g, file)
  File "addon/iris-load/loader.py", line 185, in proc
    partition_time_idx = col_name.index(g['partition_time_col_name'].lower())
ValueError: u'stime' is not in list
```

**Comment by ssm0219** [comment]
@veldise 이게 어떤 문제인지 알려주실 수 있으신가요? 당장 해결이 안된다면 우회해서라도 데이터를 IRIS에 넣어야 해서 문의 드립니다.

**Comment by hiy2259** [comment]
@ssm0219 
현제 데이터를 확인해 보니 파티션키로 지정한 컬럼에 데이터가 간간히 빠져 있습니다.
![image](https://user-images.githubusercontent.com/5515493/58296683-9fac7700-7e0f-11e9-8b36-28581c91ba52.png)
이렇게 되면 아이리스에 로딩시 에러가 납니다.
일단 데이터를 한번 확인 하시고 다시 시도해 주세요.

**Comment by ssm0219** [comment]
@hiy2259 선임님, 위 스크린샷은 열 구분자 설정이 잘못된 걸로 보이는데,

아래 스크린샷이 제가 행구분자 열구분자를 설정한 화면입니다. (위에 언급한 #1311 내 스크린샷입니다)
이거 기준으로 다시 확인해주실 수 있으신가요?

![image](https://user-images.githubusercontent.com/35832986/58296963-e0f15680-7e10-11e9-813a-a5de5c771ebc.png)

**Comment by veldise** [comment]
@ssm0219 
웹UI쪽 문제가 아니라서 답변드리기가 어렵습니다. 플랫폼연구팀 박진호 선임님께 문의 부탁드립니다.

**Comment by ssm0219** [comment]
@pjh0347 

선임님, 제가 테스트해보니 기존에 import가 되지 않던 데이터를 9등분해서 업로드 하니 모두 정상 업로드 되었습니다.

만약 해당 파일이 필요하시다면 제공해드리겠습니다.

이슈 해결에 도움이 되길 바랍니다.

**Comment by ssm0219** [comment]
https://drive.google.com/open?id=18f6eI6JTUwHVmEsskOi91gnVbzLeT19G

위 파일들은 원 데이터에서 같은 연도인 데이터들을 추출하여 CSV를 따로 만든 파일들입니다.

정확히 9등분인지는 알 수 없으나, 연도별로 나눈 파일을 '데이터 추가' 기능으로 추가했을 때는 정상적으로 잘 처리되었습니다.

**Comment by namjals** [comment]
@veldise @ssm0219 @pjh0347 
데이터에는 문제가 없어 보입니다. 
총 1,959,460개의 행이 있고 총 1,959,460개의 STIME이 있고 모든 행은 29개의 컬럼으로 이루어져 있습니다.
180번 서버에서 `docker exec -it data-trans-service bash`로 들어가보면, 임시 데이터가 생성되는`/app/tmp/0c626973-6aec-444a-b53d-922c047f3ec7` 경로로 가면 `LAPD_CRIMEDATA_from2010.csv.trans` 데이터의 크기가 0임을 확인할 수 있습니다.

`*.csv.trans` 파일은  `addon/preprocessing/proc.js`에서 만들고 있습니다. 

위의 UI로그를 보면 아래와 같이 메모리에러가 나는데, 463MB를 한번에 메모리에 올려서 `*.csv.trans`파일을 만드는 거 같습니다.
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

스트리밍 형식으로 파일을 생성하거나, JavaScript 사용시 메모리 사용량을 늘려야할 것으로 보입니다.

**Comment by veldise** [comment]
@namjals
1. `proc.js` 파일은 저희가 작성한게 아닙니다. javascript라고 다 저희가 개발하는게 아닙니다.
2. stream 방식으로 변경해야 할 것 같은데, 먼저 코드 검토 바랍니다.
이후에 공용 모듈 수정 방안에 대해 회의를 진행하는 것이 좋겠습니다.

**Comment by namjals** [comment]
대략 코드를 봤는데 `proc.js`에서는 원본파일을 `createReadStream`으로 만들어서 `addon/preprocessing/common/dataProc.js`으로 읽어달라고 요청하고, `dataProc.js`에서 `LineReader`로 원본파일을 모두 읽어서 처리하고 있습니다. 

`dataProc.js`에서 1줄씩 처리 결과를 받아서 `proc.js`에서 write하거나 `dataProc.js`에서 1줄 읽고 1줄 쓰고 이런식으로 해야할 거 같은데, javascript를 해본것도 아니고 지금 116번에서 포트를 따서 로컬에서 테스트 가능한 환경도 아니고해서... 배우면서 할라면 이것만 하면 한달정도 걸릴거 같은데요?

**Comment by namjals** [comment]
@veldise @pjh0347 
javascript 메모리를 8192MB로 늘려서 180에 배포하였습니다.
아래와 같이 원래는 `Step.1 Data Processing`에서 에러가 났는데 현재는 프로세싱 완료 후, iris에 업로드가 진행되고 있습니다.
![프로세싱 성공](https://user-images.githubusercontent.com/22319132/58606681-7f7d2c00-82d7-11e9-8a8a-50641a71478c.png)
