### ISSUE TITLE
ValueLinkU / "데이터 추가" 시 값변환 적용시 오류발생

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1406]
## 버그 설명 ##
CSV파일을 "데이터 추가" 기능에서 가동 단계의  "값변환"을 적용한 후 "제출" 실행시 오류 발생

## 재현하는 방법 ##
동작을 재현하는 방법 :
1. 데이터 추가 실행
2. 2019-03-01 01:00:00 형태의 값이 포함된 csv파일 업로드 선택
3. 값 변환 실행(3가지 변환 실행)
   "1 0" --> "10"
    "-" -->""
    ":" --> ""
4. 제출

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/62526821-f81edc80-b874-11e9-8a0a-cdb36a33275a.png)

## 로그 ##
```
새 테이블 생성에 성공 하였습니다.
데이터 전송을 시작 합니다.
Parameter Data
================================================================================
{
    "input_format": {
        "col_list": [
            "DT", 
            "HH", 
            "LON", 
            "LAT", 
            "RSRP", 
            "RSRQ", 
            "SINR", 
            "THP_DL", 
            "THP_UL", 
            "RESULT", 
            "CQI", 
            "BLUE", 
            "TX_ID", 
            "FREQ_BAND", 
            "MESHCODE3", 
            "MESHCODE4", 
            "AREA1", 
            "AREA2", 
            "AREA3", 
            "AREA3_CODE", 
            "MESH50_LON", 
            "MESH50_LAT", 
            "MESH100_LON", 
            "MESH100_LAT", 
            "MESH500_LON", 
            "MESH500_LAT"
        ], 
        "col_sep_list": [
            ","
        ], 
        "header": "1", 
        "multi_sep": "0", 
        "row_sep_list": [
            "\n", 
            "\r\n"
        ], 
        "text_qualifier": ""
    }, 
    "output_format": {
        "col_sep_list": [
            ","
        ], 
        "column_info": [
            {
                "name": "DT", 
                "type": "TEXT"
            }, 
            {
                "name": "HH", 
                "type": "TEXT"
            }, 
            {
                "name": "LON", 
                "type": "TEXT"
            }, 
            {
                "name": "LAT", 
                "type": "TEXT"
            }, 
            {
                "name": "RSRP", 
                "type": "TEXT"
            }, 
            {
                "name": "RSRQ", 
                "type": "TEXT"
            }, 
            {
                "name": "SINR", 
                "type": "TEXT"
            }, 
            {
                "name": "THP_DL", 
                "type": "TEXT"
            }, 
            {
                "name": "THP_UL", 
                "type": "TEXT"
            }, 
            {
                "name": "RESULT", 
                "type": "TEXT"
            }, 
            {
                "name": "CQI", 
                "type": "TEXT"
            }, 
            {
                "name": "BLUE", 
                "type": "TEXT"
            }, 
            {
                "name": "TX_ID", 
                "type": "TEXT"
            }, 
            {
                "name": "FREQ_BAND", 
                "type": "TEXT"
            }, 
            {
                "name": "MESHCODE3", 
                "type": "TEXT"
            }, 
            {
                "name": "MESHCODE4", 
                "type": "TEXT"
            }, 
            {
                "name": "AREA1", 
                "type": "TEXT"
            }, 
            {
                "name": "AREA2", 
                "type": "TEXT"
            }, 
            {
                "name": "AREA3", 
                "type": "TEXT"
            }, 
            {
                "name": "AREA3_CODE", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH50_LON", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH50_LAT", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH100_LON", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH100_LAT", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH500_LON", 
                "type": "TEXT"
            }, 
            {
                "name": "MESH500_LAT", 
                "type": "TEXT"
            }
        ], 
        "disk_savetime": 43200, 
        "header": "1", 
        "memory_savetime": 1440, 
        "multi_sep": "0", 
        "partition_division": "DT", 
        "partition_key": "FREQ_BAND", 
        "partition_rangetime": 60, 
        "row_sep_list": [
            "\n", 
            "\r\n"
        ], 
        "saving_method": "new", 
        "storage_type": "iris", 
        "table_method": "local", 
        "table_name": "MDT_JP.ASDFAS", 
        "text_qualifier": ""
    }, 
    "task_list": [
        {
            "func": "col_data_convert", 
            "param": {
                "col_name": "DT", 
                "conv_method": "TEXT", 
                "string_join": {
                    "back": "", 
                    "front": ""
                }, 
                "string_split": {
                    "back": "", 
                    "front": ""
                }, 
                "string_substitution": {
                    "case_sensitive": "1", 
                    "change_keyword": "", 
                    "find_keyword": "-", 
                    "regex": "0"
                }
            }
        }, 
        {
            "func": "col_data_convert", 
            "param": {
                "col_name": "DT", 
                "conv_method": "TEXT", 
                "string_join": {
                    "back": "", 
                    "front": ""
                }, 
                "string_split": {
                    "back": "", 
                    "front": ""
                }, 
                "string_substitution": {
                    "case_sensitive": "1", 
                    "change_keyword": "10", 
                    "find_keyword": "1 0", 
                    "regex": "0"
                }
            }
        }, 
        {
            "func": "col_data_convert", 
            "param": {
                "col_name": "DT", 
                "conv_method": "TEXT", 
                "string_join": {
                    "back": "", 
                    "front": ""
                }, 
                "string_split": {
                    "back": "", 
                    "front": ""
                }, 
                "string_substitution": {
                    "case_sensitive": "1", 
                    "change_keyword": "", 
                    "find_keyword": ":", 
                    "regex": "0"
                }
            }
        }
    ], 
    "upload_file_list": [
        "MDT_20190301_H00.csv"
    ]
}
--------------------------------------------------------------------------------

Data Pre-processing
================================================================================
Step.0 /app/tmp/84485766-2e20-490f-9f1c-07282dda53ce/MDT_20190301_H00.csv
Step.1 Data Processing
uncaughtException 발생 : TypeError: Cannot read property 'split' of undefined
Tue, 06 Aug 2019 09:01:05 GMT uncaughtException: Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Object.exports.col_data_convert (/app/addon/preprocessing/common/dataOp.js:438:41)
    at LineReader.<anonymous> (/app/addon/preprocessing/common/dataProc.js:125:56)
    at emitOne (events.js:116:13)
    at LineReader.emit (events.js:211:7)
    at LineReader.onLine (/app/addon/preprocessing/common/line_reader.js:54:14)
    at ReadStream.LineReader.stream.on (/app/addon/preprocessing/common/line_reader.js:39:23)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
================================================================================
Data File: ./tmp/84485766-2e20-490f-9f1c-07282dda53ce/MDT_20190301_H00.csv.trans.trans
Traceback (most recent call last):
  File "addon/iris-load/loader.py", line 257, in <module>
    main()
  File "addon/iris-load/loader.py", line 251, in main
    proc (g, file)
  File "addon/iris-load/loader.py", line 185, in proc
    partition_time_idx = col_name.index(g['partition_time_col_name'].lower())
ValueError: u'dt' is not in list
```

**Comment by JeongHeeDong** [comment]
[샘플데이터]

DT,HH,LON,LAT,RSRP,RSRQ,SINR,THP_DL,THP_UL,RESULT,CQI,BLUE,TX_ID,FREQ_BAND,MESHCODE3,MESHCODE4,AREA1,AREA2,AREA3,AREA3_CODE,MESH50_LON,MESH50_LAT,MESH100_LON,MESH100_LAT,MESH500_LON,MESH500_LAT
2019-03-01 00:43:01,0,139.58149822209882,35.764993729884175,-68.82991790771484,-7.618244171142577,16.263553619384766,86688.375,75376.0,Ok,8,9,Site1249_3,2.1G,53395416,533954163,東京都,,練馬区,13120.0,139.581536,35.765119,139.581255,35.765341,139.581271,35.76444
2019-03-01 00:52:16,0,139.5825091522972,35.764465654215826,-81.89241790771484,-11.719127655029295,-0.6354598999023438,25458.90234375,75376.0,Ok,1,9,Site1343_3,2.1G,53395416,533954163,東京都,,練馬区,13120.0,139.58265,35.764681,139.582377,35.764453,139.581271,35.76444
2019-03-01 00:48:21,0,139.5889510594635,35.76647193496319,-93.57991790771484,-7.645111083984375,14.865951538085938,90110.0234375,38309.8125,Ok,6,9,Site1724_3,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.5887,35.766555,139.58898100000002,35.766333,139.586801,35.764505
2019-03-01 00:10:58,0,139.5897421382003,35.76554066089957,-85.82991790771484,-7.054210662841798,15.419227600097654,130815.265625,75376.0,Ok,7,9,Site1724_3,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.589822,35.765667,139.590103,35.765445,139.59233,35.76457
2019-03-01 00:44:07,0,139.5943906312467,35.76399060048575,-75.51741790771484,-7.044258117675781,20.73340606689453,130474.8125,75376.0,Ok,10,9,Site1723_2,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.594278,35.76391599999999,139.594558,35.763694,139.59233,35.76457
2019-03-01 00:14:35,0,139.59570216246294,35.763024610505596,-86.14241790771484,-10.02739715576172,14.44196319580078,126966.4765625,75376.0,Ok,6,9,Site1911_1,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.595952,35.76303400000001,139.59568000000002,35.762806,139.59786,35.764634
2019-03-01 00:41:02,0,139.59018032892214,35.763789135830635,-86.51741790771484,-10.46369171142578,8.688957214355469,29790.3671875,75376.0,Ok,4,9,Site1627_1,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.590407,35.763871,139.590134,35.763642,139.59233,35.76457
2019-03-01 00:00:35,0,139.5926393872066,35.76120669755379,-58.07991790771485,-7.2954044342041025,28.43000793457031,135054.171875,75376.0,Ok,13,24,Site1721_1,2.1G,53395417,533954173,東京都,,練馬区,13120.0,139.59266599999998,35.761193,139.59239399999998,35.760964,139.59241,35.760063

**Comment by veldise** [comment]
서버 사이드의 javascript 모듈에서 발생한 에러인데, 샘플데이터로는 이슈가 재현되지 않습니다.
서버 로그 확인이 필요합니다.

**Comment by JeongHeeDong** [comment]
첨부파일로 테스트 요청 드립니다.

**Comment by veldise** [comment]
utf8 인코딩시 BOM 문자 이슈로 확인되었습니다.

@pjh0347 @namjals 
파일 데이터를 가공하기 전에 utf8 인코딩인 경우, BOM 문자를 확인하여 제거하고
`DataProc`을 사용해야 합니다. 처리 바랍니다.

**Comment by JeongHeeDong** [comment]
@veldise 책임님,
완료된 기능이면 close해 주세요

**Comment by veldise** [comment]
@anhm @seungfwani

**Comment by sunghoon** [comment]
해결된 것으로 보고 닫습니다.
