### ISSUE TITLE
objectstorage csv read 명령어 수행시 에러

### ISSUE THREAD

**Issue by veldise** [mobigen/IRIS-BigData-Platform#1701]
## 버그 설명 ##
`objectstorage csv read` 명령어 수행시 에러가 반환됩니다.

## 재현하는 방법 ##
`POST /angora/query/jobs`
```js
 { q: 'objectstorage csv read \'/root/testdev/motion.tsv\' option(connector_id \'114\', sep \',\') | search *',
     save: false,
     size: 10 } }
```
`GET /angora/query/jobs/1574222803.5832`
```js
{ type: '<class \'pyspark.sql.utils.AnalysisException\'>',
  message: '(\'Path does not exist: hdfs://192.168.100.180:9090/root/testdev/motion.tsv;\',)',
  trace: 'Traceback (most recent call last):\n  File "/app/thirdparty/spark-2.3.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco\n    return f(*a, **kw)\n  File "/usr/local/lib/python3.6/dist-packages/py4j/protocol.py", line 328, in get_return_value\n    format(target_id, ".", name), value)\npy4j.protocol.Py4JJavaError: An error occurred while calling o368473.load.\n: org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://192.168.100.180:9090/root/testdev/motion.tsv;\n\tat org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:715)\n\tat org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)\n\tat org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:389)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)\n\tat scala.collection.immutable.List.foreach(List.scala:381)\n\tat scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)\n\tat scala.collection.immutable.List.flatMap(List.scala:344)\n\tat org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:388)\n\tat org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:174)\n\tat sun.reflect.GeneratedMethodAccessor2002.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py", line 89, in run\n  File "/app/src/main/python/angora/interface/restful/handlers/query.py", line 265, in _response\n  File "/app/src/main/python/angora/core/engine.py", line 232, in query\n  File "/app/src/main/python/angora/core/engine.py", line 222, in evaluate\n  File "/app/src/main/python/angora/core/engine.py", line 198, in evaluate_partitions\n  File "/app/src/main/python/angora/cmds/impl/objectstorage.py", line 162, in execute\n  File "/app/thirdparty/spark-2.3.1-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 166, in load\n    return self._df(self._jreader.load(path))\n  File "/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py", line 1257, in __call__\n    answer, self.gateway_client, self.target_id, self.name)\n  File "/app/thirdparty/spark-2.3.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 69, in deco\n    raise AnalysisException(s.split(\': \', 1)[1], stackTrace)\npyspark.sql.utils.AnalysisException: \'Path does not exist: hdfs://192.168.100.180:9090/root/testdev/motion.tsv;\'\n' }
```

## 스크린샷
http://192.168.102.177:9002/minio/root/
위 URL로 접속 및 로그인하면 아래와 같이 파일이 존재하는 것을 확인할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/69208515-2f509980-0b97-11ea-9cb2-45ea5042d0fb.png)

**Comment by namjals** [comment]
쿼리를 아래와 같이 요청드립니다.
'objectstorage csv read \'testdev/motion.tsv\' option(connector_id \'114\', sep \',\') | search *'

기존 쿼리는 path를 부분에 `'/' + bucket이름 + '/' + object키` 를 넣었고
수정된 쿼리는 path 부분에 `object키`만 넣었습니다.

기존 쿼리
'objectstorage csv read \'/root/testdev/motion.tsv\' option(connector_id \'114\', sep \',\') | search *'

**Comment by veldise** [comment]
@namjals 
bucket 명을 지정하지 않아도 조회가 되나요?

**Comment by namjals** [comment]
@veldise
bucket은 연결정보에 등록된 bucket을 사용하고 있습니다.
버킷별로 연결정보를 추가하거나 1개의 버킷에 bucket, root, yongs로 시작하는 object키를 생성해야 할 거 같습니다.

objectstorage가 현재 minio, s3를 의미하는데, s3에서는 버킷의 의미가 도메인이며 해당 리전에 1개여야 합니다. 만약 버킷을 연결정보에서 뺀다면, 해당 리전의 모든 버킷을 대상으로 두는 꼴입니다. 그리고 특정 버킷을 연결정보에 등록하고 다른 버킷을 접근한다는게 s3입장에서 맞지가 않습니다.

만약 minio같은 경우, bucket 상관없이 접근이 가능하니 bucket명을 포함해서 조회해야 한다면, objectstorage를 minio, s3로 나누는게 맞을거 같습니다.

**Comment by veldise** [comment]
@namjals 
현재 HDFS 조회 화면에 MinIO를 추가하는 작업에서 DSMS 연결정보에 대한 내용이 잘 고려되지 않은 것 같습니다.

HDFS 조회 화면에서 HDFS의 경우 계정별로 폴더를 생성하게 되어있습니다. (개인화)
이에 따라 MinIO에서도 계정별로 bucket을 만들기로 했는데, 이 경우 연결정보에 bucket을 지정하는 것과 맞습니다.

일단 연결정보만 놓고보면, 말씀하신대로 objectstorage 연결정보는 bucket을 지정하고 이에 따라 동작하는게 맞는 것으로 생각됩니다.
그룹장님과 상의 후에 다시 말씀드리겠습니다.

**Comment by veldise** [comment]
@namjals 
이제 이해했습니다. bucket 이름 제외하고 쿼리 요청하도록 하겠습니다.

**Comment by namjals** [comment]
1) 연결 정보 bucket: 'root'
`filepath: /testdev/motion.tsv`
2) 연결 정보 bucket: ''
`filepath: /root/testdev/motion.tsv`
