### ISSUE TITLE
[전력연구원 MDA] HDFS 모델생성 오류

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1822]
## 버그 설명 ##
월별 생성된 HDFS파일 모델 생성시 오류가 발생합니다.
ex) /mda/data/BAE202W/*/*/*/%Y/%m/*.csv

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/29471177/72436304-78157f00-37e3-11ea-9d66-b6d6b688f557.png)

## 로그 ##
-- angora 로그

2020-01-15 20:29:50,569 - angora.interface.restful.handlers.datamodel - INFO - url : http://10.1.1.51:6036/angora/datamodel
2020-01-15 20:29:50,570 - angora.interface.restful.handlers.datamodel - INFO - body : 
2020-01-15 20:29:50,570 - angora.interface.restful.handlers.datamodel - INFO - arguments : {}
2020-01-15 20:29:50,579 - angora.interface.restful.server - INFO - Angora version show: [Angora v0.8.0]
2020-01-15 20:29:50,605 - werkzeug - INFO - 172.17.0.9 - - [15/Jan/2020 20:29:50] "GET /angora/_version HTTP/1.1" 200 -
2020-01-15 20:29:50,636 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:29:50] "GET /angora/datamodel HTTP/1.1" 200 -
2020-01-15 20:29:51,370 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:29:51,371 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:29:51,371 - angora.interface.restful.handlers.datamodel - INFO - url : http://10.1.1.51:6036/angora/datamodel
2020-01-15 20:29:51,372 - angora.interface.restful.handlers.datamodel - INFO - body : 
2020-01-15 20:29:51,372 - angora.interface.restful.handlers.datamodel - INFO - arguments : {}
2020-01-15 20:29:51,413 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:29:51] "GET /angora/datamodel HTTP/1.1" 200 -
2020-01-15 20:30:30,452 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:30,453 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - url : http://10.1.1.51:6036/angora/query/jobs
2020-01-15 20:30:30,453 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - body : {"q":"hdfs csv read \/mda\/data\/BAE2020W\/*\/*\/*\/%Y\/%m\/*.csv option(connector_id '4', sep ',') | search *","save":false,"size":10,"sample":true}
2020-01-15 20:30:30,454 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - arguments : {}
2020-01-15 20:30:30,454 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:30,454 - angora.interface.restful.sessions - INFO - create sid 1579087830.4549 for token cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,492 - angora.common.jhmconnector - INFO - JHM socket started [job_id : 1579087830.4549, response : {u'status': 0, u'items': {u'job_id': u'1579087830.4549'}, u'messages': u''}]
2020-01-15 20:30:31,653 - angora.interface.restful.sessions - INFO - get sid 1579087830.4549 for token cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,655 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - expect run 1
2020-01-15 20:30:31,655 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:30:31] "POST /angora/query/jobs HTTP/1.1" 200 -
2020-01-15 20:30:31,656 - angora.interface.restful.sessions - INFO - get sid 1579087830.4549 for token cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,657 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - expect run 2
2020-01-15 20:30:31,658 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - expect run 3, sid = 1579087830.4549
2020-01-15 20:30:31,658 - angora.core.engine - INFO - Evaluating a query, [hdfs csv read /mda/data/BAE2020W/*/*/*/%Y/%m/*.csv option(connector_id '4', sep ',') | search *]
2020-01-15 20:30:31,673 - angora.core.engine - INFO - Command : [<angora.cmds.impl.hdfs.HDFSCommand object at 0x7f0d5e8da410>], Args : [['csv', '/mda/data/BAE2020W/*/*/*/%Y/%m/*.csv', False, [['connector_id', '4'], ['sep', ',']]]]
2020-01-15 20:30:31,673 - angora.cmds.impl.hdfs - INFO - [hdfs] in execute
2020-01-15 20:30:31,690 - angora.common.jhmconnector - INFO - JHM connection start [job_id : 1579087830.4549]
2020-01-15 20:30:31,832 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,833 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - url : http://10.1.1.51:6036/angora/query/jobs/1579087830.4549
2020-01-15 20:30:31,833 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - body : 
2020-01-15 20:30:31,834 - angora.interface.restful.handlers.supporthandlers.backgroundresult - INFO - arguments : {}
2020-01-15 20:30:31,834 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,844 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,845 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:31,846 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:30:31] "GET /angora/ping HTTP/1.1" 200 -
2020-01-15 20:30:33,894 - angora.common.jhmconnector - INFO - JHM update complete [job_id : 1579087830.4549, response : {u'status': 0, u'messages': u''}]
2020-01-15 20:30:35,332 - angora.common.jhmconnector - INFO - JHM socket close complete [job_id : 1579087830.4549, response : {"status": 0, "messages": ""}]
2020-01-15 20:30:35,334 - angora.interface.restful.handlers.supporthandlers.backgroundresult - ERROR - ERROR message : The date expression is invalid.
2020-01-15 20:30:35,334 - root - INFO - ====== Ensure ASCII, Not used. ======
2020-01-15 20:30:35,335 - angora.interface.restful.handlers.supporthandlers.backgroundresult - ERROR - trace : Traceback (most recent call last):
  File "/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py", line 89, in run
  File "/app/src/main/python/angora/interface/restful/handlers/query.py", line 265, in _response
  File "/app/src/main/python/angora/core/engine.py", line 231, in query
  File "/app/src/main/python/angora/core/engine.py", line 221, in evaluate
  File "/app/src/main/python/angora/core/engine.py", line 197, in evaluate_partitions
  File "/app/src/main/python/angora/cmds/impl/hdfs.py", line 336, in execute
  File "/app/src/main/python/angora/cmds/impl/hdfs.py", line 268, in _get_file_list
  File "/app/src/main/python/angora/util/pathfinder.py", line 52, in __init__
PathFinderException: The date expression is invalid.

2020-01-15 20:30:35,337 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:30:35] "GET /angora/query/jobs/1579087830.4549 HTTP/1.1" 200 -
2020-01-15 20:30:50,541 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:50,542 - angora.interface.restful.sessions - INFO - header : Angora cm9vdC1kYWFkODQ5OS01NDliLTQ5ZjctYjljMy1iYjIwOWJkZDRlZTM=
2020-01-15 20:30:50,543 - werkzeug - INFO - 172.17.0.7 - - [15/Jan/2020 20:30:50] "GET /angora/ping HTTP/1.1" 200 -

**Comment by seungfwani** [comment]
작성해주신 이슈 내용과 비슷한 구성으로 폴더를 생성하여
데이터 모델 생성 및 검색을 실행하였습니다.

정상 적으로 동작을 하였고, 배포요청 하도록 하겠습니다.

![image](https://user-images.githubusercontent.com/46172579/73342464-f7b24c00-42c1-11ea-92e1-29bae71595d6.png)
![image](https://user-images.githubusercontent.com/46172579/73342501-0ef13980-42c2-11ea-8099-77d5d589747d.png)

**Comment by chohi22** [comment]
![KakaoTalk_20200211_174041495](https://user-images.githubusercontent.com/29471177/74221611-e1f74a80-4cf5-11ea-96fb-2ba9bd8b1463.jpg)
02.11 권영길팀장 오셔서 배포하고 모델 만들어 지는것 확인했습니다. 
데이터가 없는 이유는 원본파일이 없어서 모델만 만들어 봤습니다.
고생하셨습니다.
