### ISSUE TITLE
[전력연구원] 시각화 오류

### ISSUE THREAD

**Issue by chohi22** [mobigen/IRIS-BigData-Platform#1839]
## 버그 설명 ##
라인챠트 시각화 조회 요청시 아래와 같은 오류 메시지가 출력됩니다.
"angora error: <type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'lower' "
![image](https://user-images.githubusercontent.com/29471177/72775062-43c11900-3c50-11ea-981e-ce1dd90c4704.png)

## 데이터 모델 스키마 ##
![image](https://user-images.githubusercontent.com/29471177/72775259-001adf00-3c51-11ea-8ab4-0cdde989061f.png)

## 로그 ##
2020-01-21 13:14:12,592 - angora.cmds.impl.hdfs - INFO - [hdfs] df_option : {'header': 'true', 'ignore_leading_white_space': 'true', 'sep': ',', 'infer_schema': 'false', 'ignore_trailing_white_space': 'true'}
2020-01-21 13:14:14,191 - angora.cmds.impl.adv - INFO - [adv-line] Parsed arguments [Namespace(col=['eId'], col_size=500, fillna=None, filter_expr=None, func_limit=None, funcs=[['sum', 'aE']], operation='line', rel_err=0.05, row=[['date_group("rYMDHM", "1H")']], sort_expr=None, targets=None)]
2020-01-21 13:14:14,191 - angora.core.engine - INFO - Command : [<angora.cmds.impl.adv.ADVCommand object at 0x7fdbe0f4bb10>], Args : [Namespace(col=['eId'], col_size=500, fillna=None, filter_expr=None, func_limit=None, funcs=[['sum', 'aE']], operation='line', rel_err=0.05, row=[['date_group("rYMDHM", "1H")']], sort_expr=None, targets=None)]
2020-01-21 13:14:14,249 - angora.common.jhmconnector - INFO - JHM socket close complete [job_id : 1579580050.5539, response : {"status": 0, "messages": ""}]
2020-01-21 13:14:14,251 - angora.interface.restful.handlers.supporthandlers.backgroundresult - ERROR - ERROR message : 'NoneType' object has no attribute 'lower'
2020-01-21 13:14:14,251 - root - INFO - ====== Ensure ASCII, Not used. ======
2020-01-21 13:14:14,252 - angora.interface.restful.handlers.supporthandlers.backgroundresult - ERROR - trace : Traceback (most recent call last):
  File "/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py", line 89, in run
  File "/app/src/main/python/angora/interface/restful/handlers/query.py", line 265, in _response
  File "/app/src/main/python/angora/core/engine.py", line 231, in query
  File "/app/src/main/python/angora/core/engine.py", line 221, in evaluate
  File "/app/src/main/python/angora/core/engine.py", line 164, in evaluate_partitions
  File "/app/src/main/python/angora/cmds/impl/adv/__init__.py", line 132, in execute
  File "/app/src/main/python/angora/cmds/impl/adv/__init__.py", line 159, in _func_line
  File "/app/src/main/python/angora/cmds/impl/pivot.py", line 334, in execute
  File "/app/src/main/python/angora/cmds/impl/pivot.py", line 501, in preprocessing_for_pivot
  File "<string>", line 1, in <module>
  File "/app/src/main/python/angora/cmds/impl/pivot.py", line 458, in date_group
AttributeError: 'NoneType' object has no attribute 'lower'

2020-01-21 13:14:14,255 - werkzeug - INFO - 172.17.0.9 - - [21/Jan/2020 13:14:14] "GET /angora/query/jobs/1579580050.5539 HTTP/1.1" 200 -

**Comment by seungfwani** [comment]
현재 모델을 보면 `Category -> time` 부분에 선택되지 않은 컬럼인 `rYMDHM` 를 unit 정보로 주어 문제가 생기는 것으로 보입니다.

해당 부분은 코드 수정이 필요합니다.

※ 결과를 바로 확인해 보는 방법이 있습니다.
  - 데이터 모델 수정을 통해 해당 컬럼을 `time` 필드로 지정을 하여 확인 할 수 있습니다.

**Comment by seungfwani** [comment]
아래와 같이, Date/ Timestamp 일 경우
고급시각화로 unit 정보를 추가하여 동작할 수 있도록 수정하였습니다.

배포요청 하도록 하겠습니다.

![image](https://user-images.githubusercontent.com/46172579/73342636-4d86f400-42c2-11ea-90ec-6198827def9a.png)
![image](https://user-images.githubusercontent.com/46172579/73342745-84f5a080-42c2-11ea-9e67-ebaec24f3f9c.png)

**Comment by chohi22** [comment]
![KakaoTalk_20200211_174022715](https://user-images.githubusercontent.com/29471177/74221691-09e6ae00-4cf6-11ea-9edf-8fca93d531d8.jpg)
02.11 배포후 확인 완료했습니다.
