### ISSUE TITLE
교통빅데이티 플랫폼 / 테이블 스페이스 사용율 현황 "다운로드" 기능 오류

### ISSUE THREAD

**Issue by JeongHeeDong** [mobigen/IRIS-BigData-Platform#1875]
## 버그 설명 ##
테이블 스페이스 사용율 현황 "다운로드"  버튼 실행시 오류가 발생함

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/4444717/73894346-8e34cd80-48bf-11ea-8a84-84cd36a5705a.png)

[오류 발생]
![image](https://user-images.githubusercontent.com/4444717/73894364-9a208f80-48bf-11ea-90de-e0afe59b61f0.png)

**Comment by veldise** [comment]
@big-mobigen 
관련 오류 발생 시점의 cluster 서비스 로그 확인 or 제공을 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 
테이블스페이스현황 사용율 현황메뉴에 다운로드 버튼 클릭당시에 발생하는 로그를 전달드립니다.
cluster 로그내용

2020-02-07 16:20:40.694  INFO 11 --- [nio-8080-exec-4] c.m.cluster.controller.ApiController     : GET /cluster/storageManage/excelDownload?null  root
2020-02-07 16:20:40.695  INFO 11 --- [nio-8080-exec-4] c.m.c.common.utils.ExceptionManager      : java.lang.NullPointerException
2020-02-07 16:20:40.695 ERROR 11 --- [nio-8080-exec-4] c.m.c.common.utils.ExceptionManager      : exception

java.lang.NullPointerException: null
        at com.mobigen.cluster.common.utils.PropertyReader.readMessage(PropertyReader.java:47)
        at com.mobigen.cluster.common.excel.ExcelHeader.<init>(ExcelHeader.java:30)
        at com.mobigen.cluster.controller.StorageManageController.excelDownload(StorageManageController.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.mobigen.cluster.security.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:35)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at com.mobigen.cluster.security.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:35)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

iris-db에서 아래 2개 명령어는 정상적으로 실행됩니다. 
.table list *.*
.table size --summary

감사합니다.

**Comment by veldise** [comment]
@JeongHeeDong 
국가/언어설정이 잘못되었을 때 발생하는 문제로 확인되었습니다.
브라우저 쿠키 중에 `locale` 값이 `ko`, `en`, `zh`, 셋 중 하나가 아니면 위와같은 에러가 발생합니다.
문제 발생시의 브라우저 쿠키값을 확인해주시면 감사하겠습니다.

별개로 에러가 발생하지 않도록 예외처리를 하겠습니다.

**Comment by JeongHeeDong** [comment]
크롬설정에서 한글 과 영어 모두 변경하여 테스트하였으나 동일하게 오류가 발생 합니다.
![image](https://user-images.githubusercontent.com/4444717/74488717-746e3880-4f06-11ea-9687-5f901aa88b34.png)

패치되기 전에 사용할 수 있는 방법에 대해 자세히 알려 주세요

**Comment by veldise** [comment]
@JeongHeeDong 

아래와 같이 로그인 화면이나, 로그인 후 우측 상단에서 IRIS 언어설정을 변경할 수 있습니다.

![image](https://user-images.githubusercontent.com/3411842/74615541-299e2c00-5165-11ea-9959-80e1ba9c98c0.png)
![image](https://user-images.githubusercontent.com/3411842/74615544-315dd080-5165-11ea-99e6-82d919242f2a.png)

정상적으로 변경되었다면 크롬 개발자도구 기준으로 해당 도메인의 `locale` 쿠키값이 `ko`, `en`, `zh` 중 하나일 것입니다. 쿠키값을 직접 수정하시거나 언어설정을 바꾸면 정상 동작할 것으로 생각됩니다.

![image](https://user-images.githubusercontent.com/3411842/74615561-518d8f80-5165-11ea-917a-d67a2bb826f9.png)

**Comment by JeongHeeDong** [comment]
locale 값은 ko로 되어 있습니다.
그래도 에러가 발생 합니다.

![image](https://user-images.githubusercontent.com/4444717/74616586-10e54480-516c-11ea-898c-bbf6955aaaa9.png)

**Comment by veldise** [comment]
@JeongHeeDong 
죄송합니다. 제가 에러 위치를 잘못 판단했습니다.
본사 1월 30일 버전에서는 수정된 문제로, LOD 요구사항 반영한 내용과 같이 배포 요청하겠습니다.

**Comment by big-mobigen** [comment]
@JeongHeeDong @veldise 
교통빅데이터플랫폼 플랫폼사이트(https://180.148.181.193/#/)에 배포후 기능 동작을 확인하였습니다. 

감사합니다.

**Comment by veldise** [comment]
@big-mobigen
고생하셨습니다.
