### ISSUE TITLE
[ValuelinkU] Studio / 테이블 다운로드 오류

### ISSUE THREAD

**Issue by SONHOJUN** [mobigen/IRIS-BigData-Platform#1973]
## 버그 설명 ##
컨테이너 해운 > Trade Capacity 보고서의 테이블 다운로드 클릭하면 오류페이지가 보임

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
![image](https://user-images.githubusercontent.com/7067615/76053915-25ba3880-5fb2-11ea-9893-42e48cf676c9.png)

오류페이지
![image](https://user-images.githubusercontent.com/7067615/76053928-34a0eb00-5fb2-11ea-93c5-eb9cf1ca19a6.png)

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
다운로드 실행 정보:
```sql
SELECT
    TRADE AS 'Trade',
    DATA01 AS '100-999',
    DATA02 AS '1,000-1,999',
    DATA031 AS '2,000-2,999',
    DATA04 AS '3,000-3,999',
    DATA05 AS '4,000-5,099',
    DATA06 AS '5,100-7,499',
    DATA07 AS '7,500-9,999',
    DATA08 AS '10,000-12,499',
    DATA09 AS '12,500-15,099',
    DATA10 AS '15,100-17,999',
    DATA11 AS '> 18,000',
    DATA12 AS 'Total Cellular TEU',
    PERCENT AS '%'
FROM
    VALUELINKU.TB_TRARDE_CAPACITY_201906;
```

@big-mobigen 
본사에서 재현되지 않아 해당 서버 로그 확인이 필요합니다.
해당 문제가 재현될 때 studio 서비스 로그를 확인 부탁드립니다.
만약 studio 에서 별다른 문제가 발생하지 않았다면 dsms 서비스 로그도 확인 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 
studio 쪽 확인되는 로그는 다음과 같습니다. 

[sutdio 서비스 docker logs ]
2020-03-16 10:33:34.600  INFO 12 --- [o-8080-exec-359] c.mobigen.studio.common.utils.HttpUtil   : HTTP GET Request URL = http://172.20.11.56:6036/angora/ping
2020-03-16 10:33:34.600  INFO 12 --- [o-8080-exec-359] c.mobigen.studio.common.utils.HttpUtil   : Angora Token = Angora MTk0NS1kNmU3ZDFiZC1iN2Y0LTQ2ZWItYmI5My1jM2QwNjFmYTcwNDM=
2020-03-16 10:33:34.603  INFO 12 --- [o-8080-exec-359] c.m.studio.controller.CommonController   : common ping url : /studio/common/ping
2020-03-16 10:33:35.775  INFO 12 --- [o-8080-exec-365] c.m.studio.controller.DsmsController     : dsms download url : /studio/dsms/download
2020-03-16 10:33:35.775  INFO 12 --- [o-8080-exec-365] c.m.studio.service.impl.DsmsServiceImpl  : dsms download parameter : csv,20200316103345,752a6e05-5be1-4482-81da-2c6fbe350270
2020-03-16 10:33:35.775  INFO 12 --- [o-8080-exec-365] c.m.studio.service.impl.DsmsServiceImpl  : dsms download url : http://172.20.11.56:9001/dsms/v1/execute/752a6e05-5be1-4482-81da-2c6fbe350270/download?type=csv
2020-03-16 10:33:35.775  INFO 12 --- [o-8080-exec-365] c.mobigen.studio.common.utils.HttpUtil   : HTTP GET Request URL = http://172.20.11.56:9001/dsms/v1/execute/752a6e05-5be1-4482-81da-2c6fbe350270/download?type=csv
2020-03-16 10:33:35.778 ERROR 12 --- [o-8080-exec-365] c.m.studio.service.impl.DsmsServiceImpl  : dsms error status code: 404 NOT_FOUND
2020-03-16 10:33:35.778 ERROR 12 --- [o-8080-exec-365] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/dsms/download] due to exception [dsms download error]

java.lang.Exception: dsms download error
        at com.mobigen.studio.service.impl.DsmsServiceImpl.download(DsmsServiceImpl.java:84)
        at com.mobigen.studio.controller.DsmsController.downloadSearch(DsmsController.java:29)
        at jdk.internal.reflect.GeneratedMethodAccessor529.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.mobigen.studio.security.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at com.mobigen.studio.security.JWTAuthenticationFilter.doFilter(JWTAuthenticationFilter.java:36)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)


[dsms 서비스 docker logs]
120:M 16 Mar 01:35:06.078 * 100 changes in 300 seconds. Saving...
120:M 16 Mar 01:35:06.078 * Background saving started by pid 11532
11532:C 16 Mar 01:35:06.082 * DB saved on disk
11532:C 16 Mar 01:35:06.082 * RDB: 2 MB of memory used by copy-on-write
120:M 16 Mar 01:35:06.179 * Background saving terminated with success


dsms쪽은 백그라운드로 돌고있는것 외에는 없으며 dsms 쪽 전체로그 확인시 django_execute.log 에서 위에 이슈현상 발생 시 아래와 같은 로그가 찍힙니다. 

==> django_execute.log <==
[2020/03/16 01:35:59] WARNING django.request, Not Found: /dsms/v1/execute/5f439671-0bec-4b63-96e9-6b3b7159146f/download

추가적으로 studio application.properties config 파일에는 dsms 서버 uri 주소가 설정되어있습니다. 
dsms.server.uri=http://172.20.11.56:9001/dsms/v1

[master서버에서 dsms 서버 uri 주소를 curl 확인한 내용]
![image](https://user-images.githubusercontent.com/25650544/76716228-de326a00-6772-11ea-9100-b4c590f3efed.png)

바쁘시겠지만 확인 부탁 드립니다. 
감사합니다.

**Comment by veldise** [comment]
@anhm 
Studio 에서 DSMS 에 jobId: `752a6e05-5be1-4482-81da-2c6fbe350270`로 download 요청을 했는데, 전혀 다른 jobId(`5f439671-0bec-4b63-96e9-6b3b7159146f`)에 대한 로그가 확인됩니다.

DSMS 서비스쪽 확인 필요합니다.

@big-mobigen
Studio 에러 로그 발생 이전에 아래와 같은 로그가 있을 것입니다.
```
2020-03-16 10:33:35.775 INFO 12 --- [o-8080-exec-365] c.m.studio.service.impl.DsmsServiceImpl : dsms download parameter : csv,20200316103345,752a6e05-5be1-4482-81da-2c6fbe350270
```
여기서 마지막 값이 JobId 입니다.
DSMS 쪽에 동일한 값이 포함된 로그가 있는지 확인 부탁드립니다.

**Comment by big-mobigen** [comment]
@veldise 

jobid 로 검색한 dsms 쪽 로그 탐색 결과를 첨부 드립니다. 

![image](https://user-images.githubusercontent.com/25650544/76717389-8433a380-6776-11ea-9723-c47b6ea761bb.png)

docker 컨테이너(dsms) 내부시간과 host에 시간이 맞지않아 로그에서 시간대는 다르게 보이는듯 합니다.

**Comment by seungfwani** [comment]
현재 같은 보고서 다운로드가 정상적으로 진행 되는 것으로 보입니다.

![Screen Shot 2020-05-15 at 2 06 30 PM](https://user-images.githubusercontent.com/46172579/82013443-4b03ab00-96b5-11ea-8911-36e9cbebd9b0.png)
<img width="1107" alt="Screen Shot 2020-05-15 at 2 07 15 PM" src="https://user-images.githubusercontent.com/46172579/82013485-640c5c00-96b5-11ea-8d4e-f04205d51bb9.png">

**Comment by SONHOJUN** [comment]
확인했습니다.
