### ISSUE TITLE
[Analyzer] 에서 minio 데이터모델을 검색하면 에러팝업창이 뜹니다.

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2334]
## 버그 설명 ##
b-iris.mobigen.com  demo 계정 06/23 07:30 에 조회

데이터모델 : EDU_Beijing_air_2013_2017_18

어제 06/22일에도 발생한 현상입니다.
minio 데이터모델만 조회가 안됩니다.
참고로
demo.iris.tool 는 어제(06/22 아침) 는 에러가 뜨지도 않고 조회가 안되지만,
오늘은 전부 조회가 됩니다.

* b-iris.mobigen.com  analyzer 화면

<img width="801" alt="스크린샷 2020-06-23 오전 7 30 09" src="https://user-images.githubusercontent.com/5126497/85341899-4936ce00-b524-11ea-80a2-6337f85bd3e7.png">

* 실행하면 뜨는 에러 팝업창
<img width="458" alt="스크린샷 2020-06-23 오전 7 30 15" src="https://user-images.githubusercontent.com/5126497/85341904-4b992800-b524-11ea-838f-037dcaac3b64.png">

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
```json
{
  "type": "<class 'py4j.protocol.Py4JJavaError'>",
  "message": "('An error occurred while calling o4337.load.\\n', JavaObject id=o4338)",
  "trace": "Traceback (most recent call last):\n  File \"/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py\", line 92, in run\n  File \"/app/src/main/python/angora/interface/restful/handlers/query.py\", line 45, in _response\n  File \"/app/src/main/python/angora/core/engine.py\", line 236, in query\n  File \"/app/src/main/python/angora/core/engine.py\", line 226, in evaluate\n  File \"/app/src/main/python/angora/core/engine.py\", line 202, in evaluate_partitions\n  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 837, in execute\n    ret = modeltimeline.handle()\n  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 699, in handle\n    for result in self._response(results, internal_unit):\n  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 772, in _response\n    for result, status in results:\n  File \"/app/src/main/python/angora/spark/queries.py\", line 22, in execute\n  File \"/app/src/main/python/angora/spark/queries.py\", line 25, in _execute\n  File \"/app/src/main/python/angora/core/engine.py\", line 226, in evaluate\n  File \"/app/src/main/python/angora/core/engine.py\", line 202, in evaluate_partitions\n  File \"/app/src/main/python/angora/cmds/impl/objectstorage.py\", line 211, in execute\n  File \"/app/thirdparty/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/readwriter.py\", line 166, in load\n    return self._df(self._jreader.load(path))\n  File \"/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py\", line 1257, in __call__\n    answer, self.gateway_client, self.target_id, self.name)\n  File \"/app/thirdparty/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/utils.py\", line 63, in deco\n    return f(*a, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/py4j/protocol.py\", line 328, in get_return_value\n    format(target_id, \".\", name), value)\npy4j.protocol.Py4JJavaError: An error occurred while calling o4337.load.\n: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.102.177:9002 [/192.168.102.177] failed: Connection refused (Connection refused)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)\n\tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)\n\tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)\n\tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4926)\n\tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4872)\n\tat com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1321)\n\tat com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1295)\n\tat org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:903)\n\tat org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:77)\n\tat org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)\n\tat org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:557)\n\tat org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)\n\tat scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)\n\tat scala.collection.immutable.List.foreach(List.scala:392)\n\tat scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)\n\tat scala.collection.immutable.List.flatMap(List.scala:355)\n\tat org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)\n\tat org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)\n\tat org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)\n\tat org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)\n\tat sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.102.177:9002 [/192.168.102.177] failed: Connection refused (Connection refused)\n\tat org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)\n\tat org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)\n\tat sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)\n\tat com.amazonaws.http.conn.$Proxy20.connect(Unknown Source)\n\tat org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)\n\tat org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)\n\tat org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)\n\tat org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)\n\tat org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)\n\tat com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1297)\n\tat com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)\n\t... 36 more\nCaused by: java.net.ConnectException: Connection refused (Connection refused)\n\tat java.net.PlainSocketImpl.socketConnect(Native Method)\n\tat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\n\tat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\n\tat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\n\tat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n\tat java.net.Socket.connect(Socket.java:607)\n\tat org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)\n\tat org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)\n\t... 51 more\n\n"
}
```
```
Traceback (most recent call last):
  File \"/app/src/main/python/angora/interface/restful/handlers/supporthandlers/backgroundresult.py\", line 92, in run
  File \"/app/src/main/python/angora/interface/restful/handlers/query.py\", line 45, in _response
  File \"/app/src/main/python/angora/core/engine.py\", line 236, in query
  File \"/app/src/main/python/angora/core/engine.py\", line 226, in evaluate
  File \"/app/src/main/python/angora/core/engine.py\", line 202, in evaluate_partitions
  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 837, in execute
    ret = modeltimeline.handle()
  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 699, in handle
    for result in self._response(results, internal_unit):
  File \"/app/src/main/python/angora/cmds/impl/model-timeline.py\", line 772, in _response
    for result, status in results:
  File \"/app/src/main/python/angora/spark/queries.py\", line 22, in execute
  File \"/app/src/main/python/angora/spark/queries.py\", line 25, in _execute
  File \"/app/src/main/python/angora/core/engine.py\", line 226, in evaluate
  File \"/app/src/main/python/angora/core/engine.py\", line 202, in evaluate_partitions
  File \"/app/src/main/python/angora/cmds/impl/objectstorage.py\", line 211, in execute
  File \"/app/thirdparty/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/readwriter.py\", line 166, in load
    return self._df(self._jreader.load(path))
  File \"/usr/local/lib/python3.6/dist-packages/py4j/java_gateway.py\", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File \"/app/thirdparty/spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/utils.py\", line 63, in deco
    return f(*a, **kw)
  File \"/usr/local/lib/python3.6/dist-packages/py4j/protocol.py\", line 328, in get_return_value
    format(target_id, \".\", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o4337.load.
: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 192.168.102.177:9002 [/192.168.102.177] failed: Connection refused (Connection refused)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4926)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4872)
    at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1321)
    at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1295)
    at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:903)
    at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:77)
    at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:557)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary$1.apply(DataSource.scala:545)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
    at scala.collection.immutable.List.flatMap(List.scala:355)
    at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:545)
    at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:359)
    at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
    at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
    at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
    at py4j.Gateway.invoke(Gateway.java:282)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:238)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.102.177:9002 [/192.168.102.177] failed: Connection refused (Connection refused)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
    at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
    at com.amazonaws.http.conn.$Proxy20.connect(Unknown Source)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1297)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
    ... 36 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:607)
    at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    ... 51 more
```

**Comment by anhm** [comment]
mino 서버가 죽어 있는것이 확인되고 다시 실행시켜 두었습니다.
