### ISSUE TITLE
[Analyzer]의 "분석코드복사" (rest_api 스크립트) 에서 python 코드는 에러납니다.python2 버전  문제 & SSL 문제

### ISSUE THREAD

**Issue by seoryjj** [mobigen/IRIS-BigData-Platform#2480]
## 버그 설명 ##

b-iris.mobigen.com demo 계정

- 우선 3.7 python 에서 
from httplib import HTTPConnection 
대신
import http.client 
를 써야 하는데, 지금 있는 python 코드는 python2 버전 코드입니다. 

- 검색어
`model name = 'EDU_population_for_motion' model_owner = root  | WHERE population >= 100000000  | distinct country `

- import http.client  를 써서 python3 버전 코드로 수정한 후에도  ssl 관련 에러가 납니다.
```
>>> host, port = (addr, 6036)
>>> parameters = {}
>>> parameters['q'] = q
>>> parameters['save'] = True
>>> http_conn = http.client.HTTPSConnection(host, port)
>>> http_conn.request(
...     "POST",
...     "/angora/auth",
...     json.dumps({"id": user_id, "password": user_passwd}))
```
- 에러 내용
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
**ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)**
```

- 참고로 R 스크립트는 잘 동작하여 맞는 응답 데이터를 받았습니다.
```
              country
1       United States
2               China
3               India
4             Nigeria
5          Bangladesh
6  Russian Federation
7              Mexico
8           Indonesia
9              Brazil
10              Japan
11           Pakistan
```

## 재현하는 방법 ##
동작을 재현하는 방법 :

## 예상한 행동 ##
{ 위의 재현 방법에서 예상했던 것에 대한 명확하고 간결한 설명 부탁드립니다. }

## 스크린샷 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 스크린샷을 여기에 추가해 주세요 }

## 로그 ##
{ 가능한 경우 문제를 설명하는데 도움이되는 서버 혹은 브라우저의 로그를 여기에 추가해 주세요 }

## 기타 ##
{ 기타 문제에 대한 다른 상황이나 의견은 여기에 추가 부탁드립니다 }

**Comment by veldise** [comment]
@anhm @seungfwani 
python 스크립트 관련하여 지원을 부탁드립니다.

**Comment by seoryjj** [comment]
@seungfwani
KeyError: 'results'  가 나는 것 보면 예전 버전 python 인 거 같습니다.
SSL 에러는 HTTPSConnection -> HTTPConnection 으로 하니 발생하지 않습니다.

**Comment by veldise** [comment]
@seoryjj 
"Python 코드 복사하기" 를 "Python2 코드 복사하기", "Python3 코드 복사하기" 로 분리하겠습니다.
python 3은 아래와 같이 1줄만 변경하면 될까요?

```py
from httplib import HTTPConnection // 기존
from http.client import HTTPConnection // 변경
```

**Comment by seungfwani** [comment]
@veldise 
해당라인을 바꾸는 것은 맞습니다만,
python2 와 python3 간에 문법적 차이가 있습니다.
예) python2 -> `print 'a'` , python3 -> `print('a')`

그러므로 2to3 라는 pip 모듈을 이용해 변환을 하는 것이 안전 합니다.
